# Generated by Django 6.1 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_resetpasswordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='borrar_glpi_al_eliminar',
            field=models.BooleanField(
                default=False,
                help_text='Si está activo, al borrar un ticket se eliminará también del sistema GLPI.',
                verbose_name='Borrar en GLPI al eliminar',
            ),
        ),
    ]