# Generated by Django 5.2.17 on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):
    """El borrado es lógico: el ajuste de GLPI ahora aplica al purgar de la papelera."""

    dependencies = [
        ('accounts', '0007_usuario_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='borrar_glpi_al_eliminar',
            field=models.BooleanField(
                default=False,
                help_text='Si está activo, al purgar de la papelera un ticket se eliminará también del sistema GLPI.',
                verbose_name='Borrar en GLPI al purgar',
            ),
        ),
    ]
