# Generated by Django 6.1 on 2026-09-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usuario_borrar_glpi_al_purgar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bienvenida_vista',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
