# Generated by Django 6.1 on 2026-10-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usuario_bienvenida_vista'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tour_habilitado',
            field=models.BooleanField(default=True, help_text='Si está activo, el tour guiado se ofrece en todas las vistas.', verbose_name='Tour guiado activado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tour_visto',
            field=models.BooleanField(default=False, help_text='Se marca al terminar el tour guiado para no volver a mostrarlo.', verbose_name='Tour ya completado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_actividad',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Se actualiza con el latido que envía el navegador; sirve para ver quién está conectado.', null=True, verbose_name='Última actividad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('tecnico', 'Técnico'), ('usuario', 'Usuario'), ('observador', 'Observador')], default='tecnico', max_length=20),
        ),
    ]
