# Generated by Django 6.1 on 2026-09-30 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bienvenida', 'Bienvenida'), ('ticket_nuevo', 'Ticket nuevo'), ('ticket_cerrado', 'Ticket cerrado'), ('ticket_recordatorio', 'Recordatorio de tickets'), ('evento', 'Tarea o evento'), ('sistema', 'Sistema')], db_column='Tipo', default='sistema', max_length=20)),
                ('titulo', models.CharField(db_column='Titulo', max_length=140)),
                ('mensaje', models.CharField(db_column='Mensaje', max_length=300)),
                ('icono', models.CharField(db_column='Icono', default='i-bell', max_length=30)),
                ('url', models.CharField(blank=True, db_column='Url', default='', max_length=255)),
                ('clave', models.CharField(blank=True, db_column='Clave', default='', max_length=140)),
                ('leida', models.BooleanField(db_column='Leida', default=False)),
                ('mostrada_en', models.DateTimeField(blank=True, db_column='MostradaEn', null=True)),
                ('leida_en', models.DateTimeField(blank=True, db_column='LeidaEn', null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True, db_column='CreadaEn')),
                ('usuario', models.ForeignKey(db_column='UsuarioId', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'Notificaciones',
                'ordering': ['-creada_en', '-id'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='ix_notif_usuario_leida')],
            },
        ),
    ]
