# Generated by Django 6.1 on 2026-10-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('bienvenida', 'Bienvenida'), ('ticket_nuevo', 'Ticket nuevo'), ('ticket_cerrado', 'Ticket cerrado'), ('ticket_editado', 'Ticket editado'), ('ticket_recordatorio', 'Recordatorio de tickets'), ('evento', 'Tarea o evento'), ('sistema', 'Sistema')], db_column='Tipo', default='sistema', max_length=20),
        ),
    ]
