# Generated by Django 6.1 on 2026-08-07 21:34

import apps.tickets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=50, verbose_name='Grupo')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True)),
                ('glpi_category_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID categoria GLPI')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categorias',
                'ordering': ['grupo', 'nombre'],
                'unique_together': {('grupo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=12, unique=True, verbose_name='Codigo')),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en-progreso', 'En progreso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=15)),
                ('solicitante_nombre', models.CharField(max_length=100, verbose_name='Solicitante')),
                ('solicitante_email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Correo')),
                ('solicitante_punto', models.CharField(blank=True, help_text='Ej: Caja 3 Envigado, PC-P1 PC5, Server Principal', max_length=80, null=True, verbose_name='Punto / sede / equipo')),
                ('glpi_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID GLPI')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, db_column='CategoriaId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.categoria')),
                ('tecnico_asignado', models.ForeignKey(blank=True, db_column='TecnicoAsignadoId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'Tickets',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TicketAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=255)),
                ('archivo', models.FileField(max_length=500, upload_to=apps.tickets.models.adjunto_upload_to)),
                ('mime_type', models.CharField(max_length=100)),
                ('tamano_bytes', models.PositiveIntegerField()),
                ('subido_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(db_column='TicketId', on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'db_table': 'TicketAdjuntos',
                'ordering': ['fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='TicketComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_nombre', models.CharField(blank=True, default='', max_length=100)),
                ('comentario', models.TextField()),
                ('es_interno', models.BooleanField(default=False, help_text='Si es True, solo lo ve el staff')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(db_column='TicketId', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tickets.ticket')),
                ('usuario', models.ForeignKey(blank=True, db_column='UsuarioId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'TicketComentarios',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado'], name='IX_Tickets_Estado'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['prioridad'], name='IX_Tickets_Prioridad'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['fecha_creacion'], name='IX_Tickets_Fecha'),
        ),
    ]
