# Generated by Django 6.1 on 2026-08-14 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketadjunto',
            name='sincronizado_glpi',
            field=models.BooleanField(default=False, help_text='True cuando el archivo ya fue subido a GLPI como documento del ticket'),
        ),
        migrations.CreateModel(
            name='GlpiEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cambio-estado', 'Cambio de estado'), ('seguimiento', 'Nuevo seguimiento'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('payload_bruto', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(blank=True, db_column='TicketId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_glpi', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Evento GLPI',
                'verbose_name_plural': 'Eventos GLPI',
                'db_table': 'GlpiEventos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='IX_GlpiEventos_Fecha')],
            },
        ),
    ]
