# Generated by Django 5.2.17 on 2026-08-30 18:35

from django.db import migrations, models

from apps.tickets.sla import ANS_POR_PRIORIDAD


def backfill_ans_horas(apps, schema_editor):
    Categoria = apps.get_model("tickets", "Categoria")
    for prioridad, horas in ANS_POR_PRIORIDAD.items():
        Categoria.objects.filter(prioridad_default=prioridad).update(ans_horas=horas)


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_categoria_prioridad_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='ans_horas',
            field=models.PositiveIntegerField(default=24, help_text='Tiempo máximo (horas) para resolver tickets de esta categoría. Si no se define, se usa el valor base de la prioridad.', verbose_name='Horas ANS'),
        ),
        migrations.RunPython(backfill_ans_horas, migrations.RunPython.noop),
    ]
