# Generated by Django 6.1 on 2026-09-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_categoria_ans_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='modo',
            field=models.CharField(choices=[('web', 'Web Form'), ('email', 'E-Mail'), ('telefono', 'Phone Call'), ('importado', 'Importado GLPI')], default='web', help_text='Canal por el que ingresó la solicitud (portal, correo o llamada).', max_length=20, verbose_name='Modo de ingreso'),
        ),
    ]
