# Generated by Django 6.1 on 2026-09-18 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_modo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('combinar', 'Combinar'), ('vincular', 'Vincular')], default='vincular', max_length=20, verbose_name='Tipo de relación')),
                ('comentario', models.TextField(blank=True, default='', verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, db_column='CreadoPorId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('ticket_principal', models.ForeignKey(db_column='TicketPrincipalId', on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_principales', to='tickets.ticket', verbose_name='Solicitud principal')),
                ('ticket_secundario', models.ForeignKey(db_column='TicketSecundarioId', on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_secundarios', to='tickets.ticket', verbose_name='Solicitud secundaria')),
            ],
            options={
                'verbose_name': 'Vínculo de solicitud',
                'verbose_name_plural': 'Vínculos de solicitudes',
                'db_table': 'TicketVinculos',
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['ticket_secundario'], name='IX_TicketVinculos_Sec'), models.Index(fields=['ticket_principal'], name='IX_TicketVinculos_Prin')],
                'unique_together': {('ticket_principal', 'ticket_secundario', 'tipo')},
            },
        ),
    ]
