# Generated by Django 5.2.17 on 2026-09-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticketvinculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina_mostrar_redes', models.BooleanField(default=True, verbose_name='Mostrar sección de redes sociales')),
                ('correo_activo', models.BooleanField(default=True, verbose_name='Mostrar botón de correo')),
                ('correo_soporte', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo de soporte')),
                ('whatsapp_activo', models.BooleanField(default=True, verbose_name='Mostrar botón de WhatsApp')),
                ('whatsapp_numero', models.CharField(blank=True, default='3103716129', max_length=20, verbose_name='Número de WhatsApp')),
                ('tiktok_activo', models.BooleanField(default=True, verbose_name='Mostrar botón de TikTok')),
                ('tiktok_url', models.CharField(blank=True, default='', max_length=250, verbose_name='URL de TikTok')),
                ('instagram_activo', models.BooleanField(default=True, verbose_name='Mostrar botón de Instagram')),
                ('instagram_url', models.CharField(blank=True, default='', max_length=250, verbose_name='URL de Instagram')),
                ('facebook_activo', models.BooleanField(default=True, verbose_name='Mostrar botón de Facebook')),
                ('facebook_url', models.CharField(blank=True, default='', max_length=250, verbose_name='URL de Facebook')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de la página',
                'verbose_name_plural': 'Configuración de la página',
                'db_table': 'ConfigSitio',
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solicitante_punto',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Punto / sede / equipo'),
        ),
    ]
