# Generated by Django 5.2.17 on 2026-09-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0008_configsitio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, db_column='EliminadoPorId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
    ]
