# Generated by Django 6.1 on 2026-10-02 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_eliminado_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Punto o zona')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Punto o zona',
                'verbose_name_plural': 'Puntos o zonas',
                'db_table': 'Puntos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Explicación para el usuario: qué incluye esta categoría y cuándo reportar aquí.', verbose_name='Qué hace esta categoría'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='ejemplos',
            field=models.CharField(blank=True, default='', help_text='Casos típicos, separados por comas, que ayudan al autocompletado.', max_length=300, verbose_name='Ejemplos de incidentes'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tecnicos',
            field=models.ManyToManyField(blank=True, help_text='Uno o varios técnicos habilitados en esta categoría. El primero disponible gana el ticket.', related_name='categorias', to=settings.AUTH_USER_MODEL, verbose_name='Técnicos de la categoría'),
        ),
        migrations.CreateModel(
            name='ObservadorPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('observador', models.ForeignKey(db_column='ObservadorId', on_delete=django.db.models.deletion.CASCADE, related_name='puntos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Observador')),
                ('punto', models.ForeignKey(db_column='PuntoId', on_delete=django.db.models.deletion.CASCADE, related_name='observadores', to='tickets.punto', verbose_name='Punto o zona')),
            ],
            options={
                'verbose_name': 'Punto asignado al observador',
                'verbose_name_plural': 'Puntos asignados a observadores',
                'db_table': 'ObservadorPuntos',
                'ordering': ['punto__nombre'],
                'unique_together': {('observador', 'punto')},
            },
        ),
        migrations.CreateModel(
            name='ElementoMiLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('usuario', 'Usuario'), ('punto', 'Punto')], db_column='Tipo', default='usuario', max_length=10)),
                ('nota', models.CharField(blank=True, db_column='Nota', default='', max_length=200, verbose_name='Nota')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='CreadoEn')),
                ('observador', models.ForeignKey(db_column='ObservadorId', on_delete=django.db.models.deletion.CASCADE, related_name='mi_lista', to=settings.AUTH_USER_MODEL, verbose_name='Observador')),
                ('usuario', models.ForeignKey(blank=True, db_column='UsuarioId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('punto', models.ForeignKey(blank=True, db_column='PuntoId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tickets.punto', verbose_name='Punto o zona')),
            ],
            options={
                'verbose_name': 'Elemento de la lista del observador',
                'verbose_name_plural': 'Elementos de la lista de los observadores',
                'db_table': 'ElementosMiLista',
                'ordering': ['-creado_en', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('usuario__isnull', False)), fields=('observador', 'usuario'), name='uq_milista_obs_usuario'), models.UniqueConstraint(condition=models.Q(('punto__isnull', False)), fields=('observador', 'punto'), name='uq_milista_obs_punto')],
            },
        ),
    ]
