# Generated by Django 6.1

from django.db import migrations


class Migration(migrations.Migration):
    """Se retiran los campos que se agregaron a la categoría y ya no se usan.

    La vista del técnico vuelve a tener un solo técnico por defecto, sin
    descripción ni ejemplos, así que estos tres campos sobran. Se borran por
    migración y no a mano para que la base de Windows y la de desarrollo
    queden igual.
    """

    dependencies = [
        ("tickets", "0010_punto_categoria_descripcion_categoria_ejemplos_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoria",
            name="tecnicos",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="ejemplos",
        ),
    ]
