# Generated by Django 5.2.17 on 2026-10-04 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_elementomilista_usuario_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configsitio',
            name='panel_mostrar_actividad_glpi',
            field=models.BooleanField(default=True, help_text='Si está apagada, el bloque «Actividad reciente GLPI» no aparece en el panel de nadie.', verbose_name='Mostrar actividad de GLPI en los paneles'),
        ),
        migrations.CreateModel(
            name='CalificacionTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.SmallIntegerField(choices=[(1, 'Me gusta'), (-1, 'No me gusta')], verbose_name='Voto')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_hechas', to=settings.AUTH_USER_MODEL, verbose_name='Calificado por')),
            ],
            options={
                'verbose_name': 'Calificación de técnico',
                'verbose_name_plural': 'Calificaciones de técnicos',
                'db_table': 'CalificacionesTecnicos',
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('tecnico', 'usuario'), name='uq_calificacion_tecnico_usuario')],
            },
        ),
    ]
