# Generated by Django 5.2.17 on 2026-10-06 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_quitar_indice_viejo_calificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaObservador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='Nombre', max_length=80, verbose_name='Nombre de la zona')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='CreadoEn')),
                ('observador', models.ForeignKey(db_column='ObservadorId', on_delete=django.db.models.deletion.CASCADE, related_name='zonas_observador', to=settings.AUTH_USER_MODEL, verbose_name='Observador')),
            ],
            options={
                'verbose_name': 'Zona del observador',
                'verbose_name_plural': 'Zonas de los observadores',
                'db_table': 'ZonasObservador',
                'ordering': ['nombre'],
                'unique_together': {('observador', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='elementomilista',
            name='zona',
            field=models.ForeignKey(blank=True, db_column='ZonaObservadorId', help_text='Carpeta propia del observador para agrupar a quien sigue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos', to='tickets.zonaobservador', verbose_name='Zona del observador'),
        ),
    ]
