# Generated by Django 6.1 on 2026-09-21 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0007_ticketvinculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Festivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Festivo',
                'verbose_name_plural': 'Festivos',
                'db_table': 'Festivos',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='CalendarioEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarea', 'Tarea'), ('solicitud', 'Solicitud'), ('recordatorio', 'Recordatorio'), ('proyecto', 'Proyecto'), ('anuncio', 'Anuncio')], default='tarea', max_length=15)),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripcion')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('sitio', models.CharField(blank=True, default='', max_length=80, verbose_name='Sitio / punto')),
                ('grupo', models.CharField(blank=True, default='', max_length=60, verbose_name='Grupo')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, db_column='CreadoPorId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_calendario_creados', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, db_column='TecnicoId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_calendario', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, db_column='TicketId', help_text='Solicitud vinculada cuando tipo = solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_calendario', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Evento de calendario',
                'verbose_name_plural': 'Eventos de calendario',
                'db_table': 'CalendarioEventos',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('ausencia', 'Ausencia'), ('no_ausencia', 'No ausencia'), ('falta', 'Falta de disponibilidad')], default='ausencia', max_length=20, verbose_name='Tipo')),
                ('nota', models.CharField(blank=True, default='', max_length=200, verbose_name='Nota')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, db_column='CreadoPorId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disponibilidad_creada', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(db_column='TecnicoId', on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilidad de técnico',
                'verbose_name_plural': 'Disponibilidad de técnicos',
                'db_table': 'DisponibilidadTecnicos',
                'ordering': ['fecha'],
                'constraints': [models.UniqueConstraint(fields=('tecnico', 'fecha'), name='uq_disponibilidad_tecnico_fecha')],
            },
        ),
    ]
