# Generated by Django 5.2.17 on 2026-09-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadtecnico',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora'),
        ),
    ]
