-- ============================================================
--  BASE DE DATOS GLOBAL - MESA DE AYUDA DOGGER
--  VARIANTE POSTGRESQL (produccion recomendada)
--  Tipos convertidos: bigint IDENTITY, boolean, timestamp, jsonb
--  Uso: psql -U dogger -d dogger -f DB_global_proyecto_postgres.sql
-- ============================================================

BEGIN;
SET client_encoding = 'UTF8';

DROP TABLE IF EXISTS "TicketComentarios" CASCADE;
DROP TABLE IF EXISTS "TicketAdjuntos" CASCADE;
DROP TABLE IF EXISTS "GlpiEventos" CASCADE;
DROP TABLE IF EXISTS "Tickets" CASCADE;
DROP TABLE IF EXISTS "Categorias" CASCADE;
DROP TABLE IF EXISTS "Usuarios_user_permissions" CASCADE;
DROP TABLE IF EXISTS "Usuarios_groups" CASCADE;
DROP TABLE IF EXISTS "Usuarios" CASCADE;
DROP TABLE IF EXISTS "django_admin_log" CASCADE;
DROP TABLE IF EXISTS "django_session" CASCADE;
DROP TABLE IF EXISTS "django_migrations" CASCADE;
DROP TABLE IF EXISTS "auth_group_permissions" CASCADE;
DROP TABLE IF EXISTS "auth_group" CASCADE;
DROP TABLE IF EXISTS "auth_permission" CASCADE;
DROP TABLE IF EXISTS "django_content_type" CASCADE;

CREATE TABLE "Categorias" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "grupo" varchar(50) NOT NULL,
  "nombre" varchar(80) NOT NULL,
  "activo" boolean NOT NULL,
  "glpi_category_id" integer NULL CHECK ("glpi_category_id" >= 0),
  "TecnicoDefaultId" bigint NULL REFERENCES "Usuarios" ("id") DEFERRABLE INITIALLY DEFERRED,
  "prioridad_default" varchar(20) NOT NULL,
  "ans_horas" integer NOT NULL CHECK ("ans_horas" >= 0)
);

CREATE TABLE "GlpiEventos" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" varchar(20) NOT NULL,
  "descripcion" varchar(255) NOT NULL,
  "payload_bruto" jsonb NULL,
  "fecha" timestamp NOT NULL,
  "TicketId" bigint NULL REFERENCES "Tickets" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "TicketAdjuntos" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_original" varchar(255) NOT NULL,
  "archivo" varchar(500) NOT NULL,
  "mime_type" varchar(100) NOT NULL,
  "tamano_bytes" integer NOT NULL CHECK ("tamano_bytes" >= 0),
  "subido_por" varchar(100) NULL,
  "fecha_subida" timestamp NOT NULL,
  "TicketId" bigint NOT NULL REFERENCES "Tickets" ("id") DEFERRABLE INITIALLY DEFERRED,
  "sincronizado_glpi" boolean NOT NULL
);

CREATE TABLE "TicketComentarios" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "autor_nombre" varchar(100) NOT NULL,
  "comentario" text NOT NULL,
  "es_interno" boolean NOT NULL,
  "fecha" timestamp NOT NULL,
  "TicketId" bigint NOT NULL REFERENCES "Tickets" ("id") DEFERRABLE INITIALLY DEFERRED,
  "UsuarioId" bigint NULL REFERENCES "Usuarios" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "Tickets" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(12) NOT NULL UNIQUE,
  "titulo" varchar(150) NOT NULL,
  "descripcion" text NOT NULL,
  "prioridad" varchar(10) NOT NULL,
  "estado" varchar(15) NOT NULL,
  "solicitante_nombre" varchar(100) NOT NULL,
  "solicitante_email" varchar(150) NULL,
  "solicitante_punto" varchar(80) NULL,
  "glpi_id" integer NULL CHECK ("glpi_id" >= 0),
  "fecha_creacion" timestamp NOT NULL,
  "fecha_actualizacion" timestamp NOT NULL,
  "fecha_cierre" timestamp NULL,
  "CategoriaId" bigint NULL REFERENCES "Categorias" ("id") DEFERRABLE INITIALLY DEFERRED,
  "TecnicoAsignadoId" bigint NULL REFERENCES "Usuarios" ("id") DEFERRABLE INITIALLY DEFERRED,
  "asignacion_automatica" boolean NOT NULL
);

CREATE TABLE "Usuarios" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "password" varchar(128) NOT NULL,
  "last_login" timestamp NULL,
  "is_superuser" boolean NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "email" varchar(150) NOT NULL UNIQUE,
  "rol" varchar(20) NOT NULL,
  "activo" boolean NOT NULL,
  "fecha_creacion" timestamp NOT NULL,
  "is_staff" boolean NOT NULL,
  "is_active" boolean NOT NULL,
  "glpi_user_id" integer NULL CHECK ("glpi_user_id" >= 0),
  "telefono" varchar(20) NOT NULL,
  "avatar" varchar(100) NULL,
  "genero" varchar(20) NOT NULL
);

CREATE TABLE "Usuarios_groups" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" bigint NOT NULL REFERENCES "Usuarios" ("id") DEFERRABLE INITIALLY DEFERRED,
  "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "Usuarios_user_permissions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" bigint NOT NULL REFERENCES "Usuarios" ("id") DEFERRABLE INITIALLY DEFERRED,
  "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "auth_group" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) NOT NULL UNIQUE
);

CREATE TABLE "auth_group_permissions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED,
  "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE "auth_permission" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED,
  "codename" varchar(100) NOT NULL,
  "name" varchar(255) NOT NULL
);

CREATE TABLE "django_admin_log" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "object_id" text NULL,
  "object_repr" varchar(200) NOT NULL,
  "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0),
  "change_message" text NOT NULL,
  "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED,
  "user_id" bigint NOT NULL REFERENCES "Usuarios" ("id") DEFERRABLE INITIALLY DEFERRED,
  "action_time" timestamp NOT NULL
);

CREATE TABLE "django_content_type" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "app_label" varchar(100) NOT NULL,
  "model" varchar(100) NOT NULL
);

CREATE TABLE "django_migrations" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "app" varchar(255) NOT NULL,
  "name" varchar(255) NOT NULL,
  "applied" timestamp NOT NULL
);

CREATE TABLE "django_session" (
  "session_key" varchar(40) NOT NULL PRIMARY KEY,
  "session_data" text NOT NULL,
  "expire_date" timestamp NOT NULL
);

CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE UNIQUE INDEX "Usuarios_groups_usuario_id_group_id_e88b744a_uniq" ON "Usuarios_groups" ("usuario_id", "group_id");
CREATE INDEX "Usuarios_groups_usuario_id_88bd6b34" ON "Usuarios_groups" ("usuario_id");
CREATE INDEX "Usuarios_groups_group_id_890f65b0" ON "Usuarios_groups" ("group_id");
CREATE UNIQUE INDEX "Usuarios_user_permissions_usuario_id_permission_id_82ba4004_uniq" ON "Usuarios_user_permissions" ("usuario_id", "permission_id");
CREATE INDEX "Usuarios_user_permissions_usuario_id_d81d2a07" ON "Usuarios_user_permissions" ("usuario_id");
CREATE INDEX "Usuarios_user_permissions_permission_id_dd067c85" ON "Usuarios_user_permissions" ("permission_id");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE INDEX "TicketComentarios_TicketId_1c8f8877" ON "TicketComentarios" ("TicketId");
CREATE INDEX "TicketComentarios_UsuarioId_ac614a87" ON "TicketComentarios" ("UsuarioId");
CREATE INDEX "TicketAdjuntos_TicketId_31fa4058" ON "TicketAdjuntos" ("TicketId");
CREATE INDEX "GlpiEventos_TicketId_d05586b2" ON "GlpiEventos" ("TicketId");
CREATE INDEX "IX_GlpiEventos_Fecha" ON "GlpiEventos" ("fecha" DESC);
CREATE INDEX "Tickets_glpi_id_a9486641" ON "Tickets" ("glpi_id");
CREATE INDEX "Tickets_CategoriaId_a7997bf8" ON "Tickets" ("CategoriaId");
CREATE INDEX "Tickets_TecnicoAsignadoId_4da54145" ON "Tickets" ("TecnicoAsignadoId");
CREATE INDEX "IX_Tickets_Estado" ON "Tickets" ("estado");
CREATE INDEX "IX_Tickets_Prioridad" ON "Tickets" ("prioridad");
CREATE INDEX "IX_Tickets_Fecha" ON "Tickets" ("fecha_creacion");
CREATE UNIQUE INDEX "Categorias_grupo_nombre_0071b2a5_uniq" ON "Categorias" ("grupo", "nombre");
CREATE INDEX "Categorias_TecnicoDefaultId_88072feb" ON "Categorias" ("TecnicoDefaultId");

-- datos: Usuarios
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (1, 'pbkdf2_sha256$1500000$l2DiXk5ZZgGv1FSn62wikV$MU6K7ym+R52xDi+LZ6vTJlSRCRs4RP/usSlwKmdMPYg=', NULL, FALSE, 'Prueba', 'prueba@dogger.com.co', 'tecnico', TRUE, '2026-09-04 13:53:44.378406', FALSE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (2, 'pbkdf2_sha256$1500000$3kScBH3xlMBrqSCdyi1fxd$iwCqlt/c+SoLbknYJqMSbJJSdbHgOsop0YpeZXi1Ars=', '2026-09-04 16:35:09.657755', FALSE, 'Ana', 'ana@dogger.com.co', 'usuario', TRUE, '2026-09-04 16:35:09.581098', FALSE, TRUE, NULL, '', '', 'femenino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (3, 'pbkdf2_sha256$1500000$ahKbCmS2yq2PzQa8Zpzbji$nWI1Yn+gtl3f0O/bCEo/ytpWL4EMK1y1wfJ4T3J8lao=', '2026-09-04 16:51:12.026313', FALSE, 'Carlos Alberto', 'carlosalberto@dogger.com.co', 'usuario', TRUE, '2026-09-04 16:51:11.924677', FALSE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (4, 'pbkdf2_sha256$1500000$0EuZEMlO0CupWRsndK9JGv$3Gfd702WTWZekHYqDyr1sD/iHSNTKy9TX3n5h/z6j0o=', '2026-09-04 16:51:12.420711', FALSE, 'Laura', 'laura@dogger.com.co', 'usuario', TRUE, '2026-09-04 16:51:12.329693', FALSE, TRUE, NULL, '', '', 'femenino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (5, 'pbkdf2_sha256$1500000$R1KLTZkszAT3YxIDVwBtJB$/Haqri2StJJ4AoTKllRciWw3MJOVmMHR5DP4idsL+vw=', '2026-09-04 16:51:12.810341', FALSE, 'Juan', 'juan@dogger.com.co', 'usuario', TRUE, '2026-09-04 16:51:12.739221', FALSE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (6, 'pbkdf2_sha256$1500000$6UbyD8vGlEvqhiGBSMXNbU$733wcNBFX+hjUy3VANlwzkkaphPVjvlKbSgfqIPfF8s=', '2026-09-04 16:51:21.494177', FALSE, 'María Fernanda', 'mariafernanda@dogger.com.co', 'usuario', TRUE, '2026-09-04 16:51:21.408667', FALSE, TRUE, NULL, '', '', 'femenino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (7, 'pbkdf2_sha256$1500000$fS44fAREfB2tiMyC0PBOiD$cAoAGhIVruE4BFDjrfPcOHUhgin5w96C3WvZGmIqQxM=', NULL, FALSE, 'Existente', 'duplicado@dogger.com.co', 'tecnico', TRUE, '2026-09-04 17:11:53.964570', FALSE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (8, 'pbkdf2_sha256$1500000$UjkdNsEveuudcHL21XZmqX$P96fOjfJQW9OI67dodjw0QKUY4xEN5qfC9IQCGVxUJ8=', NULL, FALSE, 'Existente', 'dup2@dogger.com.co', 'tecnico', TRUE, '2026-09-04 17:12:00.229693', FALSE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (9, 'pbkdf2_sha256$1500000$qwgSipJqeW0MwhkV2sxQZ6$qFlkh4ap0hLPcrLEPwqqOT+7VNec1Id1M85cb+iTN78=', '2026-09-04 17:39:08.959573', FALSE, 'Admin', 'admin@dogger.com.co', 'admin', TRUE, '2026-09-04 17:39:07.251538', TRUE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (10, 'pbkdf2_sha256$1500000$Scr2H9FH9Jzyg9MNdDZHsX$fR+Zk3LGiC09P/NezUWElt3MEuSFMM07eWAB6t+ST0s=', '2026-09-04 17:39:08.540658', FALSE, 'Usuario', 'usuario@dogger.com.co', 'usuario', TRUE, '2026-09-04 17:39:07.575625', FALSE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (11, 'pbkdf2_sha256$1500000$SsyXZTHOpyGucYDv7CWmh4$UhXSwuZTxzyb4m6OJBD6mog73lNY3nfExxkfrrDNT2s=', '2026-09-04 18:18:30.372444', FALSE, 'L', 'l@d.com.co', 'usuario', TRUE, '2026-09-04 18:18:30.189601', FALSE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (12, 'pbkdf2_sha256$1500000$XjOII3fOXa3zdxJtbygxvm$JwMBc4Z22WIK7zipxikhkFIqHTwYzBTbEY9i3VtQ0ZE=', '2026-09-04 18:26:55.479777', FALSE, 'L', 'l2@d.com.co', 'usuario', TRUE, '2026-09-04 18:26:55.316942', FALSE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (13, 'pbkdf2_sha256$1500000$XWyjN9CO0fsx6RmFUem0k4$+zRCF2KmwfDwUfpOR6OBz7oVrGnwwnPUA7nsODwp4pY=', '2026-09-04 18:31:16.172617', FALSE, 'L', 'l3@d.com.co', 'usuario', TRUE, '2026-09-04 18:31:16.003944', FALSE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (14, 'pbkdf2_sha256$1500000$uWHIdVX5Lvoy41bCE5jfRI$EMHNnBInGlO9qXYbOK+btFHuJq/7ddZsb6dlXeTfRgs=', '2026-09-04 18:42:26.745901', FALSE, 'U', 'u@d.com.co', 'usuario', TRUE, '2026-09-04 18:42:26.250916', FALSE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (15, 'pbkdf2_sha256$1500000$SBor0cEjScX8DPZliWMVvP$ISbsDH75oLfzim07NW/eUy7bnwW0SrVTyBJV7jU3DUY=', '2026-09-04 18:42:26.928495', FALSE, 'A', 'a@d.com.co', 'admin', TRUE, '2026-09-04 18:42:26.597799', TRUE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (16, 'pbkdf2_sha256$1500000$zlWfHPplQmNgRCJdzmHrQy$hOJe4F+5peevvI+zCMc693RfCpsj/bhoPacL+qFLyi0=', '2026-09-04 19:07:00.875056', FALSE, 'U4', 'u4@d.com.co', 'usuario', TRUE, '2026-09-04 19:06:59.770052', FALSE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (17, 'pbkdf2_sha256$1500000$OnSP4RJuLJhzuVC9TPnnjb$/UTj8D6ZdOfQl9WVl9+qZFLizV+HOaEp7faczYTXL5A=', '2026-09-04 19:07:01.223849', FALSE, 'A4', 'a4@d.com.co', 'admin', TRUE, '2026-09-04 19:07:00.102992', TRUE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (18, 'pbkdf2_sha256$1500000$xSIBGShPioesF7u74wmoku$8Etbx9OR+wHZ/mUVuYZ1Q9AXMs2YigIvf5bz9e5raaY=', '2026-09-04 19:22:39.998105', FALSE, 'U5', 'u5@d.com.co', 'usuario', TRUE, '2026-09-04 19:22:39.175515', FALSE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (19, 'pbkdf2_sha256$1500000$SIFouoGxQRpGq3hQiU3m7h$cOfxcHIKomOkj5SI6wIYaeKNIAG4coH6C7iMVM5jTZg=', '2026-09-04 19:22:46.693880', FALSE, 'U6', 'u6@d.com.co', 'usuario', TRUE, '2026-09-04 19:22:45.996387', FALSE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (20, 'pbkdf2_sha256$1500000$9ATJR21tDyT6VOZtKrfmnM$0tc1NJL1iApntikvRVj/GmIVOcnwRw+WxnfNOaQ20jM=', NULL, FALSE, 'PR', 'pr@dogger.com', 'tecnico', TRUE, '2026-09-04 19:44:50.530051', FALSE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (21, 'pbkdf2_sha256$1500000$Jl3FyEwCMZOb70qVyCCzP8$EyhIzSotlbZkMOTaM5pY3NNO5TBrvLVXtI8WmJWAl7s=', NULL, FALSE, 'DBG', 'dbg@dogger.com', 'tecnico', TRUE, '2026-09-04 19:45:14.686323', FALSE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (22, 'pbkdf2_sha256$1500000$lMZDsynHzNv4Eh2LaCEBp3$Q01zI9QpfXzNhp1gc8AY6zAvZeWfdxWXZKv1CiJobxE=', NULL, FALSE, 'DBG2', 'dbg2@dogger.com', 'tecnico', TRUE, '2026-09-04 19:45:21.925091', FALSE, TRUE, NULL, '', '', 'masculino');
INSERT INTO "Usuarios" ("id", "password", "last_login", "is_superuser", "nombre", "email", "rol", "activo", "fecha_creacion", "is_staff", "is_active", "glpi_user_id", "telefono", "avatar", "genero") VALUES (23, 'pbkdf2_sha256$1500000$ctgNA2l2ACh2y6Fk3gIL8U$WqYW/LbUx8t4roBhBVNzED4kELEMMyZNiPzqbptoqFk=', NULL, FALSE, 'PR2', 'pr2@dogger.com', 'tecnico', TRUE, '2026-09-04 19:45:42.472196', FALSE, TRUE, NULL, '', '', 'masculino');

-- datos: django_session
INSERT INTO "django_session" ("session_key", "session_data", "expire_date") VALUES ('q7lg0se63d7jcjkoncq425cz9ka7wtfq', '.eJxVjMsOwiAURP-FtSFwkZdL934DAS5XqgaS0q6M_26bdKGrSeacmTcLcV1qWEeZw4TswoCdfrsU87O0HeAjtnvnubdlnhLfFX7QwW8dy-t6uH8HNY66rZUgTxa1ojNED9ITOpOjReGschqypGxISQRdIHlSCdBsCVoqkS2yzxfgfjfe:1x2Wsf:wwO07icxseaMF2qQYGGeCJap_B3N_i5SKNEDQrJhiB4', '2026-09-18 16:35:09.686495');
INSERT INTO "django_session" ("session_key", "session_data", "expire_date") VALUES ('lw4m1tbtc175uoez91c9j85oib6lyxuz', '.eJxVjEEOwiAQRe_C2hBLB4dx6b5naJgBpGogKe3KeHfbpAvdvvf-f6vRr0se1xbncQrqqqw6_TL28oxlF-Hhy71qqWWZJ9Z7og_b9FBDfN2O9u8g-5a3NZ1JojhyiUEITQoUDbBsGE2fAlLvwaI4QE7sOwuGGTuQZJzFC6jPF_WoN_c:1x2X8C:ZzwBdHoirQZSsrwhPWjIhoWB8WJCoBeeb9kYLNZjT-U', '2026-09-18 16:51:12.841873');
INSERT INTO "django_session" ("session_key", "session_data", "expire_date") VALUES ('j5lk3al1egnnjapuq1oqcgp7oa0wdmpi', '.eJxVjMsOwiAQRf-FtSHlUWBcuvcbyDBDpWogKe3K-O_apAvd3nPOfYmI21ri1vMSZxZn4cTpd0tIj1x3wHestyap1XWZk9wVedAur43z83K4fwcFe_nWOmmmMIBxJo8egwmoFTMQjINJzpuJPGGGgOC9UY7sBN4qdiloC4HE-wPXnDdo:1x2X8L:0J5g50AE3NPr-dOp-XSTmoBGBeeT5jrkvSQoFDzHf9o', '2026-09-18 16:51:21.519276');
INSERT INTO "django_session" ("session_key", "session_data", "expire_date") VALUES ('3dk13ub9q4j1vdhj54od589xhtah6ueq', '.eJxVjEEOwiAQAP_C2RAo0EKP3n0DWdjVogYMtInG-HdD0oNeZybzZh62dfFbo-oTsplJwQ6_MEC8Ue4Gr5AvhceS15oC7wnfbeOngnQ_7u3fYIG29K_WIkKwxiEqQqsMOBwUSKeUk6MVGIKVIBSN2qgBpniGKaCxwVpt3NinjVpLJXt6PlJ9sVl8vp6fPuM:1x2Xsa:LXAAIOvi0jpcx9gJHHedLnu-6unDvB5_UHokv59N7lQ', '2026-09-18 17:39:08.574015');
INSERT INTO "django_session" ("session_key", "session_data", "expire_date") VALUES ('odgf9nj3imu6rpzycy29nv6ks3hssfhx', '.eJxVjDsOwjAQBe_iGlmJ_0lJzxmsjXdNDMhGdiKBEHeHSCmgfTNvXszDusx-bVR9QjaygR1-twnClfIG8AL5XHgoealp4pvCd9r4qSDdjrv7F5ihzd-3cSYEsr3qpFQClO0iWkfWgTXDEKVGJ4JABVFEbXqDAQm1jkILjBTkFm3UWirZ0-Oe6pON3fsDhLo_Xg:1x2Xsa:EwMRMTWSDJ_SVORK4LHRjv6wfkEiymZPzPBsZjUDNNA', '2026-09-18 17:39:08.981634');
INSERT INTO "django_session" ("session_key", "session_data", "expire_date") VALUES ('998509v41ujxmhl7p6udj664si2s0whx', '.eJxVjEEOwiAQRe_C2hCGwggu3fcMZICpVA0kpV0Z765NutDtf-_9lwi0rSVsnZcwZ3ERAOL0O0ZKD647yXeqtyZTq-syR7kr8qBdji3z83q4fweFevnWGsn6QbHRKmuaSDFZsNGyAodnFw1DYh_RJzOAcei8HRAdTs5HMCqJ9wfuszcb:1x2YUg:VsmWpiZlaTCteLgtSlj_cCcMNIEgaZQEFNnSpbCFvPQ', '2026-09-18 18:18:30.389752');
INSERT INTO "django_session" ("session_key", "session_data", "expire_date") VALUES ('qzd9ipyjh0r321ekjaemn8ahk3lz6259', '.eJxVjEEOwiAURO_C2pBK4f_i0r1nIAMfpGrapLQr491Nky50O--9eauAba1ha3kJo6iLOht1-h0j0jNPO5EHpvus0zytyxj1ruiDNn2bJb-uh_t3UNHqXieJrs_kKAHZRoow3QAWAMVygum97XoPRwOxZDAVNs5a33ERdurzBTfMOJk:1x2Ycp:WRFedV3yZJX_ymMHqL2P1oO2uc0da-PBwKHqUbzITZU', '2026-09-18 18:26:55.503611');
INSERT INTO "django_session" ("session_key", "session_data", "expire_date") VALUES ('sqsp59ot5ejy8thsug04y6mnxe6e20o7', '.eJxVjMsOwiAQRf-FtSGlPDp16d5vIDMMSNVAUtqV8d-VpAvd3nPOfQmP-5b93uLqFxZnobQ4_Y6E4RFLJ3zHcqsy1LKtC8muyIM2ea0cn5fD_TvI2PK3tjAwQ0igHUaTyDAOAR2ogDSOQBYn1MmSntglZ7tjzYwEHFNSehbvDzPKOVs:1x2Yh2:FMC2P0PtZL19CmJzMsmvPUWF6Teby7_tDB8wISBTbvE', '2026-09-18 18:31:16.198981');
INSERT INTO "django_session" ("session_key", "session_data", "expire_date") VALUES ('dwze6cm5watagjqn0i1ysh4i2kl8jk4j', '.eJxVjMsOwiAQRf-FtSHA8HTp3m8gAwNSNTQp7cr479qkC93ec859sYjb2uI2yhInYmcmNTv9jgnzo_Sd0B37beZ57usyJb4r_KCDX2cqz8vh_h00HO1be6UgWfQGKjgPQFZWRwaE0NpTJaulNNmqXAJYRNJERgQMQWRXTcrs_QHjjjes:1x2Yrq:aGlT2QTB_qKT6O7MfpPcsNzCRmoAvW3xbYir3clWyLo', '2026-09-18 18:42:26.767026');
INSERT INTO "django_session" ("session_key", "session_data", "expire_date") VALUES ('ejcn37xvpjhiy7aoiif3aoagdpd0v6ad', '.eJxVjEEOwiAQRe_C2pDSAsO4dO8ZCDCDVA0kpV0Z765NutDtf-_9l_BhW4vfOi9-JnEWyojT7xhDenDdCd1DvTWZWl2XOcpdkQft8tqIn5fD_TsooZdvHadxSHp0RAyWk0ENaCc2aDNopziB1ZQNKgPEmgIpmx0MgGqKFjGJ9wf9nDer:1x2Yrq:kkt8zy8W8xH-WYs_Aou9_bbo0KzwdZuuXyMf0Soi2Ws', '2026-09-18 18:42:26.952177');
INSERT INTO "django_session" ("session_key", "session_data", "expire_date") VALUES ('2vecf3lhy79q6gi9t44gadavjwgapr9p', '.eJxVjMsOwiAUBf-FtSE8WoQu3fsN5D7QogZMaRON8d-1xoVuz8yZh4iwzGNcWppiZjEI7cTmd0Sgcyor4ROUY5VUyzxllKsiv7TJfeV02X3dv8AIbXy_DZIyaCx46Cw5ZZRXhDYov_VBQbAGNHBvnNaHTnvnLSXmwIy9RaZPtKXWci0x3a55uotBPV-TAD8m:1x2ZFc:EWNFEfmvEsT2zv3OmqJhp8cZhvXs6iVSpZ7Iblvoe3Y', '2026-09-18 19:07:00.900270');
INSERT INTO "django_session" ("session_key", "session_data", "expire_date") VALUES ('8y9ohw8vginduvnphxsb4n7w87ok92rs', '.eJxVjEEOwiAQRe_C2hBgoIwu3XsGMmWoRQ2Y0iYa4921SRe6_e_99xKBlnkMS0tTyCwOQnux-x17itdUVsIXKucqYy3zlHu5KnKjTZ4qp9txc_8CI7Xx-0ZENt50FthY5xQqHsAp6y3syYHRA9Cgeg2ANpI3ThP7ZIznLimMuEZbai3XEtLjnqenOKj3B1hKPfA:1x2ZFd:0T0kt87ex7laIRcYhmmYM8e2oHmG-kpM2sD_PSBUfoA', '2026-09-18 19:07:01.244759');
INSERT INTO "django_session" ("session_key", "session_data", "expire_date") VALUES ('54fsmzlym1ob3n4gwnowxesjhf5qw38g', '.eJxVjMsOwiAQRf-FtSHA8HTp3m8gwwBSNTQp7cr479qkC93ec859sYjb2uI2yhKnzM5Menb6HRPSo_Sd5Dv228xp7usyJb4r_KCDX-dcnpfD_TtoONq3Lk4msqai0yoA1CzIAjqfXYUqCEgn69EL5Ys2WAGNDUF5AqHIFBnY-wMQkzfk:1x2ZUm:56ROMAYMA8gHsoGMq5RyF0UeHwOm3nVxITYePMLsmto', '2026-09-18 19:22:40.034317');
INSERT INTO "django_session" ("session_key", "session_data", "expire_date") VALUES ('crrtwphe8s922o54j1xqv1hndba1qomn', '.eJxVjsEOwiAQRP-FsyGw3cXi0bvfQKALUjWQlPZk_Hdp0oNe572ZzFs4v63ZbS0ubmZxEdqK028Y_PSMZSf88OVe5VTLusxB7oo8aJO3yvF1Pdy_gexb7m2VgPVgzKgA0DKSReYzKjQaQhiU0kSJIPhRI_eArYUhUbKJIkB_9fkC07Q24g:1x2ZUs:og-2ZH7uMtGfcBDd9fAIC1Xa_MDQgTAFXvnvEweYOBs', '2026-09-18 19:22:46.712215');
INSERT INTO "django_session" ("session_key", "session_data", "expire_date") VALUES ('worancg3fccisqece4q5iwji12mojiwh', 'eyJfcGFzc3dvcmRfcmVzZXRfdG9rZW4iOiJkZWR5YXItOTkxOTcwNDc0NGFiMzZkNWEwMDdmYmJmYmY4MzFlNzYifQ:1x2ZqF:s6nvEVSxanxnr9NAY1C7QFVP9M9OPNt9Exf7V-tWsok', '2026-09-18 19:44:51.272402');
INSERT INTO "django_session" ("session_key", "session_data", "expire_date") VALUES ('5k7kenyyof2cq2b6vs959xqfyn9599jo', 'eyJfcGFzc3dvcmRfcmVzZXRfdG9rZW4iOiJkZWR5YmUtNjQzYWQ1OWEyNWFlNDQ4ZGQ2MDJhYjU0ZmQyN2Q2YzIifQ:1x2Zqd:RZ73l8584KyKByl-F9hzd9cyPgaqemC_4hdl8ZqmQJM', '2026-09-18 19:45:15.206846');
INSERT INTO "django_session" ("session_key", "session_data", "expire_date") VALUES ('cptfl5jsldjf788y3wq85ifins9p8s07', 'eyJfcGFzc3dvcmRfcmVzZXRfdG9rZW4iOiJkZWR5YmwtOWIxYmQ1NzBmYWU0YjYxMmM3ZmVlYTFjZTNiMmU5N2MifQ:1x2Zqk:kJ0YrmawmQXDDPy15TXOKZ0fM-qo0PHMMWnxweIBoDI', '2026-09-18 19:45:22.405967');
INSERT INTO "django_session" ("session_key", "session_data", "expire_date") VALUES ('wxtw19jtappiutwgjvptruqk38opiytk', 'e30:1x2Zr5:H1vWlf8BSW36oKOjYVultYxWlzCpLFeLUyH_K2drc0g', '2026-09-18 19:45:43.846479');

-- datos: django_migrations
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (1, 'contenttypes', '0001_initial', '2026-09-04 13:53:34.819845');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (2, 'contenttypes', '0002_remove_content_type_name', '2026-09-04 13:53:34.879324');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (3, 'auth', '0001_initial', '2026-09-04 13:53:35.039389');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (4, 'auth', '0002_alter_permission_name_max_length', '2026-09-04 13:53:35.141195');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (5, 'auth', '0003_alter_user_email_max_length', '2026-09-04 13:53:35.182778');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (6, 'auth', '0004_alter_user_username_opts', '2026-09-04 13:53:35.236971');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (7, 'auth', '0005_alter_user_last_login_null', '2026-09-04 13:53:35.276259');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (8, 'auth', '0006_require_contenttypes_0002', '2026-09-04 13:53:35.308264');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (9, 'auth', '0007_alter_validators_add_error_messages', '2026-09-04 13:53:35.337343');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (10, 'auth', '0008_alter_user_username_max_length', '2026-09-04 13:53:35.363538');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (11, 'auth', '0009_alter_user_last_name_max_length', '2026-09-04 13:53:35.387587');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (12, 'auth', '0010_alter_group_name_max_length', '2026-09-04 13:53:35.445239');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (13, 'auth', '0011_update_proxy_permissions', '2026-09-04 13:53:35.467940');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (14, 'auth', '0012_alter_user_first_name_max_length', '2026-09-04 13:53:35.493662');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (15, 'accounts', '0001_initial', '2026-09-04 13:53:35.612564');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (16, 'accounts', '0002_usuario_glpi_user_id', '2026-09-04 13:53:35.688435');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (17, 'accounts', '0003_usuario_telefono_avatar', '2026-09-04 13:53:35.759279');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (18, 'accounts', '0004_usuario_genero', '2026-09-04 13:53:35.811946');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (19, 'admin', '0001_initial', '2026-09-04 13:53:35.865040');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (20, 'admin', '0002_logentry_remove_auto_add', '2026-09-04 13:53:35.984719');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (21, 'admin', '0003_logentry_add_action_flag_choices', '2026-09-04 13:53:36.029945');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (22, 'sessions', '0001_initial', '2026-09-04 13:53:36.088772');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (23, 'tickets', '0001_initial', '2026-09-04 13:53:36.235293');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (24, 'tickets', '0002_ticketadjunto_sincronizado_glpi_glpievento', '2026-09-04 13:53:36.333408');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (25, 'tickets', '0003_categoria_tecnico_default_ticket_asignacion_automatica', '2026-09-04 13:53:36.534951');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (26, 'tickets', '0004_categoria_prioridad_default', '2026-09-04 13:53:36.615833');
INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES (27, 'tickets', '0005_categoria_ans_horas', '2026-09-04 13:53:36.691483');

-- datos: auth_permission
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (1, 1, 'add_logentry', 'Can add log entry');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (2, 1, 'change_logentry', 'Can change log entry');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (3, 1, 'delete_logentry', 'Can delete log entry');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (4, 1, 'view_logentry', 'Can view log entry');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (5, 3, 'add_permission', 'Can add permission');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (6, 3, 'change_permission', 'Can change permission');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (7, 3, 'delete_permission', 'Can delete permission');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (8, 3, 'view_permission', 'Can view permission');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (9, 2, 'add_group', 'Can add group');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (10, 2, 'change_group', 'Can change group');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (11, 2, 'delete_group', 'Can delete group');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (12, 2, 'view_group', 'Can view group');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (13, 4, 'add_contenttype', 'Can add content type');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (14, 4, 'change_contenttype', 'Can change content type');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (15, 4, 'delete_contenttype', 'Can delete content type');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (16, 4, 'view_contenttype', 'Can view content type');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (17, 5, 'add_session', 'Can add session');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (18, 5, 'change_session', 'Can change session');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (19, 5, 'delete_session', 'Can delete session');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (20, 5, 'view_session', 'Can view session');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (21, 6, 'add_usuario', 'Can add Usuario');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (22, 6, 'change_usuario', 'Can change Usuario');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (23, 6, 'delete_usuario', 'Can delete Usuario');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (24, 6, 'view_usuario', 'Can view Usuario');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (25, 7, 'add_categoria', 'Can add Categoria');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (26, 7, 'change_categoria', 'Can change Categoria');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (27, 7, 'delete_categoria', 'Can delete Categoria');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (28, 7, 'view_categoria', 'Can view Categoria');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (29, 9, 'add_ticket', 'Can add Ticket');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (30, 9, 'change_ticket', 'Can change Ticket');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (31, 9, 'delete_ticket', 'Can delete Ticket');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (32, 9, 'view_ticket', 'Can view Ticket');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (33, 10, 'add_ticketadjunto', 'Can add Adjunto');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (34, 10, 'change_ticketadjunto', 'Can change Adjunto');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (35, 10, 'delete_ticketadjunto', 'Can delete Adjunto');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (36, 10, 'view_ticketadjunto', 'Can view Adjunto');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (37, 11, 'add_ticketcomentario', 'Can add Comentario');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (38, 11, 'change_ticketcomentario', 'Can change Comentario');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (39, 11, 'delete_ticketcomentario', 'Can delete Comentario');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (40, 11, 'view_ticketcomentario', 'Can view Comentario');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (41, 8, 'add_glpievento', 'Can add Evento GLPI');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (42, 8, 'change_glpievento', 'Can change Evento GLPI');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (43, 8, 'delete_glpievento', 'Can delete Evento GLPI');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (44, 8, 'view_glpievento', 'Can view Evento GLPI');

-- datos: django_content_type
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (1, 'admin', 'logentry');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (2, 'auth', 'group');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (3, 'auth', 'permission');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (4, 'contenttypes', 'contenttype');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (5, 'sessions', 'session');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (6, 'accounts', 'usuario');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (7, 'tickets', 'categoria');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (8, 'tickets', 'glpievento');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (9, 'tickets', 'ticket');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (10, 'tickets', 'ticketadjunto');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES (11, 'tickets', 'ticketcomentario');

-- reiniciar secuencias de identidad

SELECT setval(pg_get_serial_sequence('"Categorias"', 'id'), 1, false);
SELECT setval(pg_get_serial_sequence('"GlpiEventos"', 'id'), 1, false);
SELECT setval(pg_get_serial_sequence('"TicketAdjuntos"', 'id'), 1, false);
SELECT setval(pg_get_serial_sequence('"TicketComentarios"', 'id'), 1, false);
SELECT setval(pg_get_serial_sequence('"Tickets"', 'id'), 1, false);
SELECT setval(pg_get_serial_sequence('"Usuarios"', 'id'), 23, true);
SELECT setval(pg_get_serial_sequence('"Usuarios_groups"', 'id'), 1, false);
SELECT setval(pg_get_serial_sequence('"Usuarios_user_permissions"', 'id'), 1, false);
SELECT setval(pg_get_serial_sequence('"auth_group"', 'id'), 1, false);
SELECT setval(pg_get_serial_sequence('"auth_group_permissions"', 'id'), 1, false);
SELECT setval(pg_get_serial_sequence('"auth_permission"', 'id'), 44, true);
SELECT setval(pg_get_serial_sequence('"django_admin_log"', 'id'), 1, false);
SELECT setval(pg_get_serial_sequence('"django_content_type"', 'id'), 11, true);
SELECT setval(pg_get_serial_sequence('"django_migrations"', 'id'), 27, true);

COMMIT;
